In [1]:
import numpy as np
np.random.seed(42)
# matrix of random numbers
a = np.random.randn(3,3)
a

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [2]:
import torch
torch.manual_seed(42)
# matrix of random numbers
a = torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [7]:
torch.LongTensor([1.0,2.0])

tensor([1, 2])